name: NiChart_DLMUSE building test for macos

# workflow dispatch has been added for testing purposes
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ["macos-latest"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Set-up miniconda for macos and ubuntu
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          miniconda-version: "latest"
      - name: Create conda env
        run: conda create -n NCP python=3.8
      - name: Install pip
        run: conda run -n NCP conda install pip
      - name: Build NiChart_DLMUSE from source
        run: |
          pip install setuptools twine wheel
          python setup.py bdist_wheel
          cd dist
          WHEEL_FILE=$(ls NiChart_DLMUSE*)
          pip install "$WHEEL_FILE"
